version: 2

project_name: sql2csv

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: sql2csv_cgo_linux
    main: ./cmd/sql2csv
    binary: sql2csv
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: sql2csv_nocgo
    main: ./cmd/sql2csv
    binary: sql2csv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    goarm:
      - 7
    ignore:
      - goos: linux
        goarch: amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

release:
  draft: true

archives:
  - id: sql2csv
    format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
